### ISSUE TITLE
Demo link

### ISSUE THREAD

**Issue by rwwagner90** [willviles/ember-cli-markdown-resolver#1]
The demo link just links to the repo. Where is the demo?

**Comment by willviles** [comment]
@rwwagner90 - not quite ready just yet! I'll notify you when it's pushed to gh-pages 👍

**Comment by willviles** [comment]
@rwwagner90 - guides are added! https://willviles.github.io/ember-cli-markdown-resolver/

**Comment by rwwagner90** [comment]
Awesome, thanks @willviles! I've been building https://github.com/shipshapecode/ember-journal with the intent of passing in models for each blog post, but I would love to support that and markdown files with this. If you feel like helping out, I'd love to have some other contributors 😄
